# Security: This file is never shared or uploaded to GitHub
ALGOLIA_APP_ID = "UTWRXU85I6"
ALGOLIA_API_KEY = "1bc09980a83d9036d4c37b76e1d74db2"
ALGOLIA_AGENT_ID = "b1ee9fb7-5e39-4a67-8d8a-1dedb8e09d75"

# Generative AI Keys
GEMINI_API_KEY = "AIzaSyDMNqxNK9FN-k7Mbc-_jplMJruPH9fy_SY"
GROQ_API_KEY = "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"